In [ ]:
#1. Install pandas

!pip install pandas

In [1]:
# 2. Importing pandas:

import pandas as pd

In [15]:
#3. Creating a DataFrame:

data = {
    'Name': ['shiva', 'pratik', 'ram', 'prashant', 'rohit', 'manohar', ],
    'Age': [25, 30, 35, 36, 18, 21,],
    'City': ['solapur', 'pune', 'Nagpur', 'solapur', 'pune', 'mumbai']
}

df = pd.DataFrame(data)
df

       Name  Age     City
0     shiva   25  solapur
1    pratik   30     pune
2       ram   35   Nagpur
3  prashant   36  solapur
4     rohit   18     pune
5   manohar   21   mumbai

In [ ]:
# 4. Basic DataFrame Operations:
df.head()       # Show first 3 rows
df.info()       # Summary of the DataFrame
df.describe()   # Statistical summary of numeric columns
df['Age']       # Access a single column
df.iloc[0]      # Access first row
df[df['Age'] > 30]  # Filter rows

In [16]:
df.head(3)

     Name  Age     City
0   shiva   25  solapur
1  pratik   30     pune
2     ram   35   Nagpur

In [17]:
df.info()
# It gives you:

# 1 Total number of rows
# 2 Total number of columns
# 3 Column names
# 4 Number of non-null (non-missing) values in each column
# 5 Data type (dtype) of each column
# 6 Memory usage of the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     6 non-null      int64
 2   City    6 non-null      object
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes

In [18]:
df.describe()

             Age
count   6.000000
mean   27.500000
std     7.395945
min    18.000000
25%    22.000000
50%    27.500000
75%    33.750000
max    36.000000

In [19]:
df['Age']

0    25
1    30
2    35
3    36
4    18
5    21
Name: Age, dtype: int64

In [20]:
df['City']

0    solapur
1       pune
2     Nagpur
3    solapur
4       pune
5     mumbai
Name: City, dtype: object

In [24]:
df['Name']

0       shiva
1      pratik
2         ram
3    prashant
4       rohit
5     manohar
Name: Name, dtype: object

In [21]:
df.iloc[0]

Name      shiva
Age          25
City    solapur
Name: 0, dtype: object

In [22]:
df.iloc[4]

Name    rohit
Age        18
City     pune
Name: 4, dtype: object

In [23]:
df[df['Age'] > 30]

       Name  Age     City
2       ram   35   Nagpur
3  prashant   36  solapur